apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template-project.deploymentName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "template-project.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "template-project.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "template-project.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "template-project.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          # secret
          {{- if .Values.global.enabledComponents.secrets }}
          envFrom:
            - secretRef:
                name: {{ include "template-project.secretName" . }}
          {{- end }}
          # configmap
          {{- if .Values.global.enabledComponents.configmap }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/src/main/resources/application.properties
              subPath: application.properties
          {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}

      {{- if .Values.global.enabledComponents.configmap }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "template-project.configmapName" . }}
      {{- end }}