{{- if .Values.global.enabledComponents.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template-project.secretName" . }}
  namespace: {{ .Values.global.namespace }}
type: {{ .Values.secrets.type }}
stringData:
  {{- toYaml .Values.secrets.stringData | nindent 2 }}
{{- end }}